USE SZPITAL	

-----------------------CREATE-----------------------

CREATE TABLE OSOBY(
	ID_OSOBY INT IDENTITY(1,1) PRIMARY KEY,
	IMIE VARCHAR(20) NOT NULL,
	NAZWISKO VARCHAR(20) NOT NULL,
	PESEL CHAR(11) CHECK(PESEL LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
	UNIQUE(PESEL)
	);

CREATE TABLE SALE(
	ID_SALI INT IDENTITY(1,1) PRIMARY KEY, 
	NUMER_SALI INT CHECK(NUMER_SALI>=1 AND NUMER_SALI<=20) NOT NULL,
	ODDZIAL VARCHAR(50) NOT NULL,
	ILOSC_OSOB INT CHECK(ILOSC_OSOB>=1 AND ILOSC_OSOB<=6)
	);

CREATE TABLE PACJENCI(
	ID_PACJENTA INT IDENTITY(1,1) PRIMARY KEY,
	DANE_PACJENTA INT REFERENCES OSOBY(ID_OSOBY) ON DELETE CASCADE NOT NULL,
	ID_SALI INT REFERENCES SALE ON DELETE SET NULL
	);

CREATE TABLE LEKARZE(
	ID_LEKARZA INT IDENTITY(1,1) PRIMARY KEY,
	DANE_LEKARZA INT REFERENCES OSOBY(ID_OSOBY) ON DELETE CASCADE NOT NULL,
	SPECJALIZACJA VARCHAR(30),
	DOSWIADCZENIE INT CHECK(DOSWIADCZENIE > 0 AND DOSWIADCZENIE <= 70),
	ORDYNATOR INT REFERENCES LEKARZE(ID_LEKARZA) DEFAULT(NULL)
	);

CREATE TABLE OPERACJE(
	ID_OPERACJI INT IDENTITY(1,1) PRIMARY KEY,
	NAZWA_OPERACJI VARCHAR(50) NOT NULL,
	ID_PACJENTA INT REFERENCES PACJENCI ON DELETE CASCADE NOT NULL,
	DATA_OPERACJI DATE NOT NULL,
	POZIOM_SKOMPLIKOWANIA INT CHECK(POZIOM_SKOMPLIKOWANIA > 0 AND POZIOM_SKOMPLIKOWANIA <= 10)
	);

CREATE TABLE CHOROBY(
	ID_CHOROBY INT IDENTITY(1,1) PRIMARY KEY,
	ICD_10 CHAR(5) NOT NULL,
	ZAKAZNOSC INT CHECK(ZAKAZNOSC > 0 AND ZAKAZNOSC <= 10)
	);

CREATE TABLE STAN_ZDROWIA(
	ID_STANU_ZDROWIA INT IDENTITY(1,1) PRIMARY KEY,
	ID_PACJENTA INT REFERENCES PACJENCI ON DELETE CASCADE NOT NULL,
	ID_CHOROBY INT REFERENCES CHOROBY ON DELETE CASCADE NOT NULL,
	DATA_ROZPOZNANIA_CHOROBY DATE NOT NULL,
	DATA_WYLECZENIA_CHOROBY DATE
	);

CREATE TABLE LEKI(
	NAZWA_LEKU VARCHAR(50) CHECK(LEN(NAZWA_LEKU)>=1) PRIMARY KEY,
	SUBSTANCJA_CZYNNA VARCHAR(50) CHECK(LEN(SUBSTANCJA_CZYNNA)>=1) NOT NULL
	);

CREATE TABLE LECZENIE(
	ID_LECZENIA INT IDENTITY(1,1) PRIMARY KEY,
	ID_PACJENTA INT REFERENCES PACJENCI ON DELETE CASCADE NOT NULL,
	NAZWA_LEKU VARCHAR(50) CHECK(LEN(NAZWA_LEKU)>=1) REFERENCES LEKI ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	DATA_ROZPOCZECIA_LECZENIA DATE NOT NULL,
	DATA_ZAKONCZENIA_LECZENIA DATE
	);

CREATE TABLE ZESPOLY_LEKARSKIE(
	ID_ZESPOLU INT IDENTITY(1,1) PRIMARY KEY,
	ID_OPERACJI INT REFERENCES OPERACJE ON DELETE NO ACTION NOT NULL,
	ID_LEKARZA INT REFERENCES LEKARZE ON DELETE CASCADE NOT NULL
	);