-----------------------DROP-----------------------

USE SZPITAL
DROP TABLE ZESPOLY_LEKARSKIE
DROP TABLE LECZENIE
DROP TABLE LEKI
DROP TABLE STAN_ZDROWIA
DROP TABLE CHOROBY
DROP TABLE OPERACJE
DROP TABLE LEKARZE
DROP TABLE PACJENCI
DROP TABLE OSOBY
DROP TABLE SALE