USE SZPITAL

INSERT INTO CHOROBY
VALUES  ('A15.0', 5),
		('B89.1', null),
		('C00.2', null),
		('D09.2', null),
		('D55.7', 3),
		('E10.8', null),
		('F11.2', null),
		('G09.3', 8),
		('H05.6', 6),
		('U07.2', 7);

INSERT INTO LEKI
VALUES  ('Lipitor', 'atorwastatyna'),
		('Humira', 'adalimumab'),
		('Nexium', 'esomeprazol'),
		('Advair', 'fluticasone'),
		('Enbrel', 'etanercept'),
		('Epogen', 'erytopoetyna'),
		('Remicade', 'infliksymab'),
		('Abilify', 'arypiprazol'),
		('Neulasta', 'pegfilgrastim'),
		('Plavix', 'klopidogrel');

INSERT INTO OSOBY 
VALUES	('Maciej', 'Wójcik', '51060575757'),
		('Alexander', 'Mazurek', '61100972871'),
		('Dawid', 'Jakubowski', '49052639231'),
		('Gracjan', 'Cieœlak', '90040775918'),
		('Karol', 'Mazur', '84062382797'),
		('Wiktoria', 'Zalewska', '60061246285'),
		('Maja', 'Rutkowska', '93080116785'),
		('Elwira', 'Brzeziñska', '95051229368'),
		('Nikola', 'Górska', '86091822181'),
		('Lucyna', 'Zalewska', '58112346729'),
		('Izyda', 'Koz³owska', '66052661185'),
		('Elena', 'Duda', '88091097727'),
		('Daria', 'Szewczyk', '03301385849'),
		('Amanda', 'Zawadzka', '51102392348'),
		('Amelia', 'Piotrowska', '68011355766'),
		('Jêdrzej', 'D¹browski', '56020631216'),
		('Gabriel', 'Lewandowski', '86110799614'),
		('Norbert', 'Brzeziñski', '54030835433'),
		('Ernest', 'Jasiñski', '70081027577'),
		('Amir', 'Soko³owski', '92041962216');

INSERT INTO SALE
VALUES  (1, 'Oddzia³ Anestezjologii', 2),
		(2, 'Oddzia³ Chirurgii Ogólnej', 4),
		(3, 'Oddzia³ Chorób Wewnêtrznych', 6),
		(4, 'Oddzia³ Kardiologiczny', 3),
		(5, 'Oddzia³ Kardiologiczny', 1),
		(1, 'Oddzia³ Kardiologiczny', null),
		(2, 'Oddzia³ Pediatryczny', 5),
		(3, 'Oddzia³ Po³o¿niczy', 2),
		(4, 'Oddzia³ Psychiatryczny', 2),
		(5, 'Oddzia³ Chorób ZakaŸnych', null);

INSERT INTO LEKARZE
VALUES  ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '66052661185'), 'Anestezjologia', 10, null),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '88091097727'), 'Chirurgia ogólna', 15, null),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '03301385849'), 'Choroby wewnêtrzne', 3, 8),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '51102392348'), 'Choroby zakaŸne', 20, null),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '68011355766'), 'Kardiologia', 7, null),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '56020631216'), 'Choroby wewnêtrzne', 5, 8),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '86110799614'), 'Choroby zakaŸne', 31, null),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '54030835433'), 'Choroby wewnêtrzne', 17, null),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '92041962216'), 'Kardiologia', null, 5),
		((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '70081027577'), 'Anestezjologia', 1, 1);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '51060575757'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 1 AND ODDZIAL = 'Oddzia³ Anestezjologii'));

	INSERT INTO OPERACJE VALUES ('operacja Bassiniego', IDENT_CURRENT('PACJENCI'), '2021-03-19', 3);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'A15.0'), '2021-03-01', '2021-02-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'atorwastatyna'), '2021-01-01', null);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '61100972871'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 1 AND ODDZIAL = 'Oddzia³ Anestezjologii'));

	INSERT INTO OPERACJE VALUES ('operacja Billrotha', IDENT_CURRENT('PACJENCI'), '2021-03-19', 1);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'G09.3'), '2021-01-01', '2021-02-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'adalimumab'), '2021-01-01', '2021-02-01');


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '49052639231'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 2 AND ODDZIAL = 'Oddzia³ Chirurgii Ogólnej'));

	INSERT INTO OPERACJE VALUES ('operacja Brickera', IDENT_CURRENT('PACJENCI'), '2021-03-19', 9);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'B89.1'), '2021-03-01', '2021-04-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'adalimumab'), '2021-01-01', '2021-02-01');


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '90040775918'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 3 AND ODDZIAL = 'Oddzia³ Chorób Wewnêtrznych'));

	INSERT INTO OPERACJE VALUES ('operacja Drapanasa', IDENT_CURRENT('PACJENCI'), '2021-03-19', 2);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'C00.2'), '2021-01-01', '2021-02-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'esomeprazol'), '2021-01-01', null);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '84062382797'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 4 AND ODDZIAL = 'Oddzia³ Kardiologiczny'));

	INSERT INTO OPERACJE VALUES ('operacja Girarda', IDENT_CURRENT('PACJENCI'), '2021-03-19', 7);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'C00.2'), '2021-03-01', '2021-04-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'esomeprazol'), '2021-01-01', null);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '60061246285'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 5 AND ODDZIAL = 'Oddzia³ Kardiologiczny'));

	INSERT INTO OPERACJE VALUES ('operacja Halstedta', IDENT_CURRENT('PACJENCI'), '2021-03-19', 9);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'U07.2'), '2021-01-01', '2021-02-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'esomeprazol'), '2021-01-01', null);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '93080116785'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 4 AND ODDZIAL = 'Oddzia³ Psychiatryczny'));

	INSERT INTO OPERACJE VALUES ('operacja Hartmanna', IDENT_CURRENT('PACJENCI'), '2021-03-19', 3);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'H05.6'), '2021-01-01', '2021-02-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'klopidogrel'), '2021-01-01', null);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '95051229368'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 3 AND ODDZIAL = 'Oddzia³ Chorób Wewnêtrznych'));

	INSERT INTO OPERACJE VALUES ('operacja Jurasza', IDENT_CURRENT('PACJENCI'), '2021-03-19', 1);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'U07.2'), '2021-01-01', '2021-02-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'klopidogrel'), '2021-01-01', null);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '86091822181'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 5 AND ODDZIAL = 'Oddzia³ Chorób ZakaŸnych'));

	INSERT INTO OPERACJE VALUES ('operacja Lichtensteina', IDENT_CURRENT('PACJENCI'), '2021-03-19', 3);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'H05.6'), '2021-01-01', '2021-02-01');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'infliksymab'), '2021-01-01', null);


INSERT INTO PACJENCI VALUES ((SELECT ID_OSOBY FROM OSOBY WHERE PESEL = '58112346729'), (SELECT ID_SALI FROM SALE WHERE NUMER_SALI = 5 AND ODDZIAL = 'Oddzia³ Chorób ZakaŸnych'));

	INSERT INTO OPERACJE VALUES ('operacja Milesa', IDENT_CURRENT('PACJENCI'), '2021-03-19', 8);
	INSERT INTO OPERACJE VALUES ('operacja Jurasza', IDENT_CURRENT('PACJENCI'), '2021-03-20', 1);

	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'A15.0'), '2021-01-01', '2021-02-01');
	INSERT INTO STAN_ZDROWIA VALUES (IDENT_CURRENT('PACJENCI'), (SELECT ID_CHOROBY FROM CHOROBY WHERE ICD_10 = 'U07.2'), '2021-01-02', '2021-02-10');

	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'infliksymab'), '2021-01-01', '2021-03-19');
	INSERT INTO LECZENIE VALUES (IDENT_CURRENT('PACJENCI'), (SELECT TOP(1) NAZWA_LEKU FROM LEKI WHERE SUBSTANCJA_CZYNNA = 'klopidogrel'), '2021-01-02', '2021-03-19');


INSERT INTO ZESPOLY_LEKARSKIE
VALUES  ((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Bassiniego' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Anestezjologia')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Bassiniego' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Chirurgia ogólna')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Girarda' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Kardiologia')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Billrotha' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Anestezjologia')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Billrotha' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Choroby zakaŸne')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Billrotha' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Kardiologia')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Brickera' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Choroby wewnêtrzne')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Brickera' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Kardiologia')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Drapanasa' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Anestezjologia')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Drapanasa' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Choroby zakaŸne')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Hartmanna' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Kardiologia')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Halstedta' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Chirurgia ogólna')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Jurasza' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Choroby zakaŸne')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Lichtensteina' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Chirurgia ogólna')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Milesa' AND DATA_OPERACJI = '2021-03-19'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Choroby wewnêtrzne')),
		((SELECT ID_OPERACJI FROM OPERACJE WHERE NAZWA_OPERACJI = 'operacja Jurasza' AND DATA_OPERACJI = '2021-03-20'), (SELECT TOP(1) ID_LEKARZA FROM LEKARZE WHERE SPECJALIZACJA = 'Chirurgia ogólna'));

SELECT * FROM CHOROBY
SELECT * FROM LEKI
SELECT * FROM OSOBY
SELECT * FROM SALE
SELECT * FROM LEKARZE
SELECT * FROM ZESPOLY_LEKARSKIE
SELECT * FROM PACJENCI
SELECT * FROM OPERACJE
SELECT * FROM STAN_ZDROWIA
SELECT * FROM LECZENIE