USE SZPITAL

-----------------------DELETE-----------------------

SELECT * FROM OSOBY
SELECT * FROM LEKARZE

DELETE FROM OSOBY WHERE PESEL = '92041962216'

SELECT * FROM OSOBY
SELECT * FROM LEKARZE

-----------------------UPDATE-----------------------

SELECT * FROM LEKI
SELECT * FROM LECZENIE

UPDATE LEKI SET NAZWA_LEKU = 'UPDATED' WHERE SUBSTANCJA_CZYNNA = 'klopidogrel'

SELECT * FROM LEKI
SELECT * FROM LECZENIE